# Generated by Django 2.1.5 on 2020-03-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('barrio', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
    ]
