# Generated by Django 2.1.5 on 2020-03-20 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='fecha_denuncia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
