# Generated by Django 3.1.7 on 2021-04-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdido', '0005_auto_20200414_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdido',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='perdido',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='perdido',
            name='recompensa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perdido',
            name='ultima_posicion_conocida',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
