# Generated by Django 3.1.7 on 2021-04-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdido', '0006_auto_20210415_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perdido',
            options={},
        ),
        migrations.RemoveField(
            model_name='perdido',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='perdido',
            name='ciudad',
        ),
    ]
