# Generated by Django 3.1.7 on 2021-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdido', '0007_auto_20210415_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdido',
            name='fecha_denuncia',
            field=models.DateTimeField(null=True),
        ),
    ]
