# Generated by Django 3.1.7 on 2021-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20200414_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='recompensa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
