# Generated by Django 3.1.7 on 2021-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20210406_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ultima_posicion_conocida',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='barrio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='ciudad',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
