# Generated by Django 3.1.7 on 2021-04-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20210412_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
