# Generated by Django 3.1.7 on 2021-04-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20210412_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='recompensa',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='ultima_posicion_conocida',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=20),
        ),
    ]
