# Generated by Django 3.1.7 on 2021-04-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210410_2027'),
        ('mascota', '0008_auto_20210415_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
